use crate::CosmeticItem;

pub fn purifying_gel_cleanser() -> CosmeticItem {
    CosmeticItem {
        id: "kc-cosm-001".to_string(),
        name: "KoColor Purifying Gel Cleanser".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "Skincare & Prep".to_string(),
        micro_category: "CLEANSER".to_string(),
        formulation: "GEL".to_string(),
        chemistry_base: "WATER".to_string(),
        finish: "MATTE".to_string(),
        coverage: "SHEER".to_string(),
        temperature: "NEUTRAL".to_string(),
        color_hex: "#F4F6F0".to_string(),
        shade_name: Some("Clear Crystal".to_string()),
        image_url: "https://cdn.kocolor.com/inventory/assets/purifying_gel_cleanser.webp".to_string(),
        notes: Some("A botanical gel cleanser that dissolves impurities while maintaining essential skin hydration and natural pH.".to_string()),
        instructions: Some("Apply 1-2 pumps to damp skin, massage gently in circular motions for 60 seconds, and rinse with lukewarm water.".to_string()),
        batch_code: Some("KC-2026-A1".to_string()),
        pao_months: Some(12),
        price: Some(32.0),
        volume: Some("150ml".to_string()),
        expiry_date: Some(1798761600000),
        hero_ingredient: Some("Niacinamide & Green Tea Extract".to_string()),
        skin_compatibility: Some("All Skin Types, Sensitive Skin Safe".to_string()),
        contains_fragrance: Some(false),
        ingredients: vec![
            "Water/Aqua".to_string(),
            "Glycerin".to_string(),
            "Sodium Cocoyl Isethionate".to_string(),
            "Niacidamide".to_string(),
            "Camellia Sinensis Leaf Extract".to_string(),
            "Cocamidopropyl Betaine".to_string(),
            "Phenoxyethanol".to_string(),
            "Ethylhexylglycerin".to_string(),
        ],
        allergens: vec![],
        eco_score: Some("A".to_string()),
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: Some("Rinse bottle, detach pump mechanism, and dispose of bottle in glass/aluminum stream according to local facility guidelines.".to_string()),
        ritual_placement: Some("Morning Routine (Step 1)".to_string()),
        fda_recall_status: Some("Clear".to_string()),
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![
            "Salicylic Acid 0.5%".to_string()
        ],
        is_fda_checked: true,
    }
}

pub fn luminescent_c_serum() -> CosmeticItem {
    CosmeticItem {
        id: "kc-cosm-002".to_string(),
        name: "KoColor Luminescent C Serum".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "Skincare & Prep".to_string(),
        micro_category: "SERUM".to_string(),
        formulation: "LIQUID".to_string(),
        chemistry_base: "WATER".to_string(),
        finish: "RADIANT".to_string(),
        coverage: "SHEER".to_string(),
        temperature: "NEUTRAL".to_string(),
        color_hex: "#FFF8E7".to_string(),
        shade_name: Some("Luminous Glow".to_string()),
        image_url: "https://cdn.kocolor.com/inventory/assets/luminescent_c_serum.webp".to_string(),
        notes: Some("High-potency antioxidant serum formulated with stabilized Vitamin C to brighten tone and shield against environmental stressors.".to_string()),
        instructions: Some("Dispense 3-4 drops onto fingertips and press gently into cleansed face, neck, and décolletage prior to moisturizing.".to_string()),
        batch_code: Some("KC-2026-B2".to_string()),
        pao_months: Some(6),
        price: Some(68.0),
        volume: Some("30ml".to_string()),
        expiry_date: Some(1798761600000),
        hero_ingredient: Some("15% L-Ascorbic Acid & Ferulic Acid".to_string()),
        skin_compatibility: Some("Normal, Combination, Dry".to_string()),
        contains_fragrance: Some(false),
        ingredients: vec![
            "Water/Aqua".to_string(),
            "Ascorbic Acid".to_string(),
            "Ethoxydiglycol".to_string(),
            "Alpha-Tocopherol".to_string(),
            "Ferulic Acid".to_string(),
            "Sodium Hyaluronate".to_string(),
            "Panthenol".to_string(),
            "Triethanolamine".to_string(),
        ],
        allergens: vec![],
        eco_score: Some("A".to_string()),
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: Some("Recycle amber glass bottle in glass waste stream. Remove dropper assembly prior to disposal.".to_string()),
        ritual_placement: Some("Morning Routine (Step 3)".to_string()),
        fda_recall_status: Some("Clear".to_string()),
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![
            "Ascorbic Acid 15%".to_string()
        ],
        is_fda_checked: true,
    }
}

pub fn anthelios_sunscreen() -> CosmeticItem {
    CosmeticItem {
        id: "kc-cosm-084".to_string(),
        name: "Anthelios Melt-in Milk Sunscreen".to_string(),
        brand: "La Roche-Posay".to_string(),
        macro_category: "Skincare & Prep".to_string(),
        micro_category: "SPF".to_string(),
        formulation: "CREAM".to_string(),
        chemistry_base: "WATER".to_string(),
        finish: "SATIN".to_string(),
        coverage: "SHEER".to_string(),
        temperature: "NEUTRAL".to_string(),
        color_hex: "#FFFFFF".to_string(),
        shade_name: Some("Invisible Shield".to_string()),
        image_url: "https://cdn.kocolor.com/inventory/assets/la_roche_posay_anthelios_melt_in_milk_sunscreen.webp".to_string(),
        notes: Some("Award-winning broad spectrum SPF 60 melt-in lotion engineered with Cell-Ox Shield technology.".to_string()),
        instructions: Some("Apply liberally 15 minutes before sun exposure; reapply every 2 hours.".to_string()),
        batch_code: Some("KC-2026-SEED".to_string()),
        pao_months: Some(12),
        price: Some(35.0),
        volume: Some("150ml".to_string()),
        expiry_date: Some(1798761600000),
        hero_ingredient: Some("Avobenzone 3% & Tocopherol".to_string()),
        skin_compatibility: Some("Sensitive, All Skin Types, Dermatologist Tested".to_string()),
        contains_fragrance: Some(false),
        ingredients: vec!["Water/Aqua".to_string(), "Avobenzone".to_string(), "Homosalate".to_string(), "Octisalate".to_string(), "Octocrylene".to_string(), "Glycerin".to_string(), "Tocopherol".to_string()],
        allergens: vec![],
        eco_score: Some("A".to_string()),
        is_vegan: Some(true),
        is_cruelty_free: Some(false),
        recycling_instructions: Some("Recycle tube via plastic curbside stream.".to_string()),
        ritual_placement: Some("Morning Routine (Step 4)".to_string()),
        fda_recall_status: Some("Clear".to_string()),
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec!["Avobenzone 3%".to_string(), "Homosalate 10%".to_string(), "Octisalate 5%".to_string(), "Octocrylene 7%".to_string()],
        is_fda_checked: true,
    }
}
