[package_metadata]
id = "kocolor-prep-vault"
name = "The Prep Ritual"
description = "Skincare foundation: Cleansers, Toners, and Serums."

[assortment]
includes = [
    "kc-exfoliant-901",
    "kc-face-mask-901",
    "kc-moisturizer-901",
    "kc-prep-01",
    "kc-prep-02",
    "kc-prep-03",
    "kc-prep-104",
    "kc-prep-105",
    "kc-primer-901",
    "kc-toner-901"
]
