[package_metadata]
id = "com.kocolor.pack.fashion.complete"
name = "Complete Fashion Vault"
description = "The full V1.0 wardrobe."

[assortment]
includes = [
    "kc-active-801",
    "kc-active-802",
    "kc-active-803",
    "kc-active-804",
    "kc-active-805",
    "kc-active-806",
    "kc-active-807",
    "kc-active-808",
    "kc-active-809",
    "kc-dresses-601",
    "kc-dresses-602",
    "kc-dresses-603",
    "kc-dresses-604",
    "kc-dresses-605",
    "kc-dresses-606",
    "kc-dresses-607",
    "kc-dresses-608",
    "kc-dresses-609",
    "kc-outerwear-701",
    "kc-outerwear-702",
    "kc-outerwear-703",
    "kc-outerwear-704",
    "kc-outerwear-705",
    "kc-outerwear-706",
    "kc-outerwear-707",
    "kc-outerwear-708",
    "kc-outerwear-709",
    "kc-pants-401",
    "kc-pants-402",
    "kc-pants-403",
    "kc-pants-404",
    "kc-pants-405",
    "kc-pants-406",
    "kc-pants-407",
    "kc-pants-408",
    "kc-pants-409",
    "kc-shirts-301",
    "kc-shirts-302",
    "kc-shirts-303",
    "kc-shirts-304",
    "kc-shirts-305",
    "kc-shirts-306",
    "kc-shirts-307",
    "kc-shirts-308",
    "kc-shirts-309",
    "kc-shoes-501",
    "kc-shoes-502",
    "kc-shoes-503",
    "kc-shoes-504",
    "kc-shoes-505",
    "kc-shoes-506",
    "kc-shoes-507",
    "kc-shoes-508",
    "kc-shoes-509"
]
