use crate::{CosmeticItem, ClothingItem};

pub fn get_default_cosmetics() -> Vec<CosmeticItem> {
    vec![
        CosmeticItem {
            id: "lip_round_trip_001".to_string(),
            name: "Glow Catalyst Lip Stain".to_string(),
            brand: "KoColor Atelier".to_string(),
            macro_category: "Lips".to_string(),
            micro_category: "Lipstick".to_string(),
            formulation: "Liquid".to_string(),
            chemistry_base: "Water".to_string(),
            finish: "Radiant".to_string(),
            coverage: "Buildable".to_string(),
            temperature: "Cool".to_string(),
            color_hex: "#800020".to_string(),
            shade_name: Some("Velvet Mulberry".to_string()),
            image_url: "https://cdn.kocolor.com/inventory/assets/velvet_mulberry.webp".to_string(),
            notes: Some("A high-tech hybrid lip stain that provides weightless color and deep hydration.".to_string()),
            instructions: Some("Apply one coat for a blurred look. Layer for intense saturation.".to_string()),
            batch_code: Some("KC-LIP-2026-ST1".to_string()),
            pao_months: Some(12),
            price: Some(34.0),
            volume: Some("5ml".to_string()),
            expiry_date: Some(1798761600000), // 2027
            hero_ingredient: Some("Hyaluronic Acid".to_string()),
            skin_compatibility: Some("All skin types".to_string()),
            contains_fragrance: Some(false),
            ingredients: vec![
                "Water".to_string(),
                "Glycerin".to_string(),
                "Red 7 Lake".to_string(),
                "Hyaluronic Acid".to_string(),
                "Tocopherol".to_string(),
            ],
            allergens: vec![],
            eco_score: Some("A".to_string()),
            is_vegan: Some(true),
            is_cruelty_free: Some(true),
            recycling_instructions: Some("Packaging is 100% recyclable. Return to store for points.".to_string()),
            ritual_placement: Some("Morning Routine (Step 8)".to_string()),
            fda_recall_status: Some("Clear".to_string()),
            fda_adverse_event_count: 0,
            fda_clinical_warnings: vec!["For external use only.".to_string()],
            fda_top_reactions: vec![],
            fda_active_ingredients: vec![],
            is_fda_checked: true,
        },
        CosmeticItem {
            id: "cosmetic_002".to_string(),
            name: "KoColor Velvet Canvas Primer".to_string(),
            brand: "KoColor".to_string(),
            macro_category: "Skincare & Prep".to_string(),
            micro_category: "Primer".to_string(),
            formulation: "Gel".to_string(),
            chemistry_base: "Silicone".to_string(),
            finish: "Matte".to_string(),
            coverage: "Sheer".to_string(),
            temperature: "Neutral".to_string(),
            color_hex: "#FFFFFF".to_string(),
            shade_name: Some("Clear".to_string()),
            image_url: "https://cdn.kocolor.com/inventory/assets/image_velvet_primer.webp".to_string(),
            notes: Some("Pore-blurring primer for a glass-skin foundation base.".to_string()),
            instructions: Some("Apply a pea-sized amount after SPF and before foundation.".to_string()),
            batch_code: Some("KC-PRM-2026-B2".to_string()),
            pao_months: Some(12),
            price: Some(42.0),
            volume: Some("30ml".to_string()),
            expiry_date: Some(1798761600000),
            hero_ingredient: Some("Niacinamide".to_string()),
            skin_compatibility: Some("Oily to Combination".to_string()),
            contains_fragrance: Some(false),
            ingredients: vec!["Dimethicone".to_string(), "Niacinamide".to_string(), "Silica".to_string(), "Aqua".to_string()],
            allergens: vec![],
            eco_score: Some("B".to_string()),
            is_vegan: Some(true),
            is_cruelty_free: Some(true),
            recycling_instructions: Some("Glass bottle is recyclable. Pump should be disposed of separately.".to_string()),
            ritual_placement: Some("Morning Routine (Step 6)".to_string()),
            fda_recall_status: Some("Clear".to_string()),
            fda_adverse_event_count: 0,
            fda_clinical_warnings: vec![],
            fda_top_reactions: vec![],
            fda_active_ingredients: vec![],
            is_fda_checked: true,
        },
    ]
}

pub fn get_default_clothing() -> Vec<ClothingItem> {
    vec![]
}
