use crate::CosmeticItem;

pub fn seamless_silk_foundation() -> CosmeticItem {
    CosmeticItem {
        id: "kc-starter-complexion-01".to_string(),
        name: "Seamless Silk Foundation".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "COMPLEXION".to_string(),
        micro_category: "FOUNDATION".to_string(),
        color_hex: "#E0AC81".to_string(),
        shade_name: Some("Warm Silk 220W".to_string()),
        image_url: "https://cdn.kocolor.com/assets/products/foundation.png".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/assets/thumbs/foundation_256.png".to_string(),
        price: Some(34.0),
        notes: Some("Buildable medium coverage foundation with a natural skin finish.".to_string()),
        formulation: Some("LIQUID".to_string()),
        chemistry_base: Some("SILICONE".to_string()),
        finish: Some("SATIN".to_string()),
        coverage: Some("MEDIUM".to_string()),
        temperature: Some("WARM".to_string()),
        volume: Some("30ml".to_string()),
        pao_months: Some(12),
        expiry_date: None,
        batch_code: None,
        hero_ingredient: Some("Hyaluronic Acid".to_string()),
        skin_compatibility: Some("All Skin Types".to_string()),
        contains_fragrance: Some(false),
        eco_score: Some("B".to_string()),
        instructions: Some("Pump onto back of hand and blend outwards using a brush.".to_string()),
        ingredients: vec!["Dimethicone".to_string(), "Water".to_string(), "Isododecane".to_string(), "Titanium Dioxide".to_string()],
        allergens: vec![],
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: None,
        ritual_placement: None,
        fda_recall_status: None,
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}

pub fn everyday_clear_concealer() -> CosmeticItem {
    CosmeticItem {
        id: "kc-starter-complexion-02".to_string(),
        name: "Everyday Clear Concealer".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "COMPLEXION".to_string(),
        micro_category: "CONCEALER".to_string(),
        color_hex: "#D4A373".to_string(),
        shade_name: Some("Warm Beige".to_string()),
        image_url: "https://cdn.kocolor.com/assets/products/concealer.png".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/assets/thumbs/concealer_256.png".to_string(),
        price: Some(16.0),
        notes: Some("Crease-resistant spot and under-eye corrector.".to_string()),
        formulation: Some("LIQUID".to_string()),
        chemistry_base: Some("WATER".to_string()),
        finish: Some("NATURAL".to_string()),
        coverage: Some("FULL".to_string()),
        temperature: Some("WARM".to_string()),
        volume: Some("8ml".to_string()),
        pao_months: Some(12),
        expiry_date: None,
        batch_code: None,
        hero_ingredient: Some("Glycerin".to_string()),
        skin_compatibility: Some("All Skin Types".to_string()),
        contains_fragrance: Some(false),
        eco_score: Some("B".to_string()),
        instructions: Some("Dab lightly onto areas needing coverage and tap to blend.".to_string()),
        ingredients: vec!["Water".to_string(), "Glycerin".to_string(), "Cyclopentasiloxane".to_string(), "Iron Oxides".to_string()],
        allergens: vec![],
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: None,
        ritual_placement: None,
        fda_recall_status: None,
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}
