use crate::CosmeticItem;

pub fn seamless_silk_foundation() -> CosmeticItem {
    CosmeticItem {
        id: "kc-cosm-003".to_string(),
        name: "KoColor Seamless Silk Foundation".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "Complexion".to_string(),
        micro_category: "FOUNDATION".to_string(),
        formulation: "LIQUID".to_string(),
        chemistry_base: "SILICONE".to_string(),
        finish: "SATIN".to_string(),
        coverage: "MEDIUM".to_string(),
        temperature: "WARM".to_string(),
        color_hex: "#E0AC81".to_string(),
        shade_name: Some("Warm Silk 220W".to_string()),
        image_url: "https://cdn.kocolor.com/inventory/assets/seamless_silk_foundation.webp".to_string(),
        notes: Some("Weightless medium-coverage liquid foundation engineered to balance oil and moisture while delivering a natural satin finish.".to_string()),
        instructions: Some("Shake well before use. Dispense 1 pump onto the back of your hand and blend outward using the KoColor Precision Sculpting Brush.".to_string()),
        batch_code: Some("KC-2026-F3".to_string()),
        pao_months: Some(12),
        price: Some(54.0),
        volume: Some("30ml".to_string()),
        expiry_date: Some(1798761600000),
        hero_ingredient: Some("Hyaluronic Acid Spheres & Squalane".to_string()),
        skin_compatibility: Some("All Skin Types".to_string()),
        contains_fragrance: Some(false),
        ingredients: vec![
            "Dimethicone".to_string(),
            "Water/Aqua".to_string(),
            "Isododecane".to_string(),
            "Polysilicone-11".to_string(),
            "Titanium Dioxide".to_string(),
            "Iron Oxides".to_string(),
            "Squalane".to_string(),
            "Sodium Hyaluronate".to_string(),
            "Tocopheryl Acetate".to_string(),
        ],
        allergens: vec![],
        eco_score: Some("B".to_string()),
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: Some("Separate pump top from glass bottle. Rinse bottle thoroughly before placing in curbside recycling.".to_string()),
        ritual_placement: Some("Base Application (Step 5)".to_string()),
        fda_recall_status: Some("Clear".to_string()),
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![
            "Titanium Dioxide 4.2%".to_string()
        ],
        is_fda_checked: true,
    }
}
