use crate::CosmeticItem;

pub fn petal_touch_blush() -> CosmeticItem {
    CosmeticItem {
        id: "kc-cosm-004".to_string(),
        name: "KoColor Petal Touch Flush Blush".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "DIMENSION".to_string(),
        micro_category: "BLUSH".to_string(),
        formulation: Some("CREAM".to_string()),
        chemistry_base: Some("OIL".to_string()),
        finish: Some("SATIN".to_string()),
        coverage: Some("MEDIUM".to_string()),
        temperature: Some("WARM".to_string()),
        color_hex: "#E07A7A".to_string(),
        shade_name: Some("Warm Rosewood".to_string()),
        image_url: "https://cdn.kocolor.com/inventory/assets/petal_touch_flush_blush.webp".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/inventory/assets/petal_touch_flush_blush_thumb.webp".to_string(),
        notes: Some("Nourishing cream blush that melts on contact with skin to produce a dewy, natural-looking flush with buildable pigments.".to_string()),
        instructions: Some("Dab onto cheeks using fingertips or a dense blush brush, then diffuse upward toward temples for an elevated lifted look.".to_string()),
        batch_code: Some("KC-2026-B4".to_string()),
        pao_months: Some(18),
        price: Some(36.0),
        volume: Some("8g".to_string()),
        expiry_date: Some(1798761600000),
        hero_ingredient: Some("Jojoba Seed Oil & Vitamin E".to_string()),
        skin_compatibility: Some("Dry, Normal, Combination".to_string()),
        contains_fragrance: Some(false),
        ingredients: vec![
            "Caprylic/Capric Triglyceride".to_string(),
            "Simmondsia Chinensis (Jojoba) Seed Oil".to_string(),
            "Euphorbia Cerifera (Candelilla) Wax".to_string(),
            "Mica".to_string(),
            "Red 7 Lake".to_string(),
            "Iron Oxides".to_string(),
            "Tocopherol".to_string(),
        ],
        allergens: vec![],
        eco_score: Some("A".to_string()),
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: Some("Compact crafted from 100% PCR aluminum. Place directly in aluminum recycling.".to_string()),
        ritual_placement: Some("Dimension Application (Step 7)".to_string()),
        fda_recall_status: Some("Clear".to_string()),
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}
