use crate::CosmeticItem;

pub fn petal_touch_flush_blush() -> CosmeticItem {
    CosmeticItem {
        id: "kc-starter-dimension-01".to_string(),
        name: "Petal Touch Flush Blush".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "DIMENSION".to_string(),
        micro_category: "BLUSH".to_string(),
        color_hex: "#C86D7C".to_string(),
        shade_name: Some("Warm Rosewood".to_string()),
        image_url: "https://cdn.kocolor.com/assets/products/blush.png".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/assets/thumbs/blush_256.png".to_string(),
        price: Some(20.0),
        notes: Some("Soft velvet blush powder that brightens the complexion.".to_string()),
        formulation: Some("POWDER".to_string()),
        chemistry_base: Some("SILICONE".to_string()),
        finish: Some("NATURAL".to_string()),
        coverage: Some("BUILDABLE".to_string()),
        temperature: Some("WARM".to_string()),
        volume: Some("6g".to_string()),
        pao_months: Some(24),
        expiry_date: None,
        batch_code: None,
        hero_ingredient: Some("Vitamin E".to_string()),
        skin_compatibility: Some("All Skin Types".to_string()),
        contains_fragrance: Some(false),
        eco_score: Some("A".to_string()),
        instructions: Some("Sweep over the apples of cheeks using a blush brush.".to_string()),
        ingredients: vec!["Mica".to_string(), "Talc".to_string(), "Dimethicone".to_string(), "Zinc Stearate".to_string()],
        allergens: vec![],
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: None,
        ritual_placement: None,
        fda_recall_status: None,
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}
