use crate::CosmeticItem;

pub fn lash_lift_mascara() -> CosmeticItem {
    CosmeticItem {
        id: "kc-starter-eyes-01".to_string(),
        name: "Lash Lift Defining Mascara".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "EYES".to_string(),
        micro_category: "MASCARA".to_string(),
        color_hex: "#1A1A1A".to_string(),
        shade_name: Some("Soft Black".to_string()),
        image_url: "https://cdn.kocolor.com/assets/products/mascara.png".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/assets/thumbs/mascara_256.png".to_string(),
        price: Some(14.0),
        notes: Some("Defining mascara for instant lift and separation.".to_string()),
        formulation: Some("LIQUID".to_string()),
        chemistry_base: Some("WAX".to_string()),
        finish: Some("MATTE".to_string()),
        coverage: Some("BUILDABLE".to_string()),
        temperature: Some("NEUTRAL".to_string()),
        volume: Some("8ml".to_string()),
        pao_months: Some(6),
        expiry_date: None,
        batch_code: None,
        hero_ingredient: Some("Carnauba Wax".to_string()),
        skin_compatibility: Some("Ophthalmologist Tested".to_string()),
        contains_fragrance: Some(false),
        eco_score: Some("B".to_string()),
        instructions: Some("Wiggle brush at the base of lashes and sweep through to tips.".to_string()),
        ingredients: vec!["Water".to_string(), "Carnauba Wax".to_string(), "Stearic Acid".to_string(), "Iron Oxides".to_string()],
        allergens: vec![],
        is_vegan: Some(false),
        is_cruelty_free: Some(true),
        recycling_instructions: None,
        ritual_placement: None,
        fda_recall_status: None,
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}
