use crate::CosmeticItem;

pub fn glow_catalyst_lip_stain() -> CosmeticItem {
    CosmeticItem {
        id: "kc-cosm-005".to_string(),
        name: "Glow Catalyst Lip Stain".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "LIPS".to_string(),
        micro_category: "LIPSTICK".to_string(),
        formulation: Some("CREAM".to_string()),
        chemistry_base: Some("OIL".to_string()),
        finish: Some("SATIN".to_string()),
        coverage: Some("FULL".to_string()),
        temperature: Some("NEUTRAL".to_string()),
        color_hex: "#A81C28".to_string(),
        shade_name: Some("Signature Crimson".to_string()),
        image_url: "https://cdn.kocolor.com/inventory/assets/signature_crimson_lipstick.webp".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/inventory/assets/signature_crimson_lipstick_thumb.webp".to_string(),
        notes: Some("Rich, iconic neutral red formulated for maximum color payoff, ultra-comfortable texture, and non-drying all-day wear.".to_string()),
        instructions: Some("Apply directly from bullet starting at the center of upper lip (cupid's bow) and moving along contour to outer corners.".to_string()),
        batch_code: Some("KC-2023-L5".to_string()),
        pao_months: Some(24),
        price: Some(42.0),
        volume: Some("3.8g".to_string()),
        expiry_date: Some(1798761600000),
        hero_ingredient: Some("Wild Mango Butter & Botanical Peptides".to_string()),
        skin_compatibility: Some("All Skin Types".to_string()),
        contains_fragrance: Some(false),
        ingredients: vec![
            "Ricinus Communis (Castor) Seed Oil".to_string(),
            "Octyldodecanol".to_string(),
            "Irvingia Gabonensis Kernel Butter".to_string(),
            "Candelilla Cera".to_string(),
            "Red 6 Lake".to_string(),
            "Red 7 Lake".to_string(),
            "Iron Oxides".to_string(),
            "Tocopheryl Acetate".to_string(),
        ],
        allergens: vec![],
        eco_score: Some("A".to_string()),
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: Some("Refillable magnetic casing. Keep outer shell and order formula bullet refills to eliminate single-use packaging waste.".to_string()),
        ritual_placement: Some("Morning Routine (Step 8)".to_string()),
        fda_recall_status: Some("Clear".to_string()),
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}

pub fn colourpop_blotted_lip() -> CosmeticItem {
    CosmeticItem {
        id: "kc-cosm-026".to_string(),
        name: "Blotted Lip".to_string(),
        brand: "ColourPop".to_string(),
        macro_category: "LIPS".to_string(),
        micro_category: "LIPSTICK".to_string(),
        formulation: Some("STICK".to_string()),
        chemistry_base: Some("WAX".to_string()),
        finish: Some("MATTE".to_string()),
        coverage: Some("SHEER".to_string()),
        temperature: Some("WARM".to_string()),
        color_hex: "#B72227".to_string(),
        shade_name: Some("Bee's Knees Crimson".to_string()),
        image_url: "https://cdn.kocolor.com/inventory/assets/colourpop_blotted_lip.webp".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/inventory/assets/colourpop_blotted_lip_thumb.webp".to_string(),
        notes: Some("Sheer matte lipstick formula giving that effortless 'just-blotted' stained lip look.".to_string()),
        instructions: Some("Swipe once for subtle stain or layer for deeper tint.".to_string()),
        batch_code: Some("KC-2026-SEED".to_string()),
        pao_months: Some(12),
        price: Some(5.5),
        volume: Some("1.0g".to_string()),
        expiry_date: Some(1798761600000),
        hero_ingredient: Some("Lauryl Laurate & Synthetic Wax".to_string()),
        skin_compatibility: Some("All Lip Types".to_string()),
        contains_fragrance: Some(false),
        ingredients: vec!["Dimethicone".to_string(), "Synthetic Wax".to_string(), "Polyethylene".to_string(), "Red 7 Lake".to_string(), "Iron Oxides".to_string()],
        allergens: vec![],
        eco_score: Some("A".to_string()),
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: Some("Recycle slim plastic casing in plastic waste.".to_string()),
        ritual_placement: Some("Lip Application (Step 8)".to_string()),
        fda_recall_status: Some("Clear".to_string()),
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}
