use crate::CosmeticItem;

pub fn glow_catalyst_lip_stain() -> CosmeticItem {
    CosmeticItem {
        id: "kc-starter-lips-01".to_string(),
        name: "Glow Catalyst Lip Stain".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "LIPS".to_string(),
        micro_category: "LIP_TINT_STAIN".to_string(),
        color_hex: "#A81C28".to_string(),
        shade_name: Some("Signature Crimson".to_string()),
        image_url: "https://cdn.kocolor.com/assets/products/stain.png".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/assets/thumbs/stain_256.png".to_string(),
        price: Some(18.0),
        notes: Some("Long-wearing hydrating lip tint.".to_string()),
        formulation: Some("LIQUID".to_string()),
        chemistry_base: Some("WATER".to_string()),
        finish: Some("SATIN".to_string()),
        coverage: Some("FULL".to_string()),
        temperature: Some("COOL".to_string()),
        volume: Some("5ml".to_string()),
        pao_months: Some(12),
        expiry_date: None,
        batch_code: None,
        hero_ingredient: Some("Tocopherol".to_string()),
        skin_compatibility: Some("All Lip Types".to_string()),
        contains_fragrance: Some(false),
        eco_score: Some("A".to_string()),
        instructions: Some("Glide applicator across lips. Reapply for bolder coverage.".to_string()),
        ingredients: vec!["Water".to_string(), "Octyldodecanol".to_string(), "Red 28".to_string(), "Tocopherol".to_string()],
        allergens: vec![],
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: None,
        ritual_placement: None,
        fda_recall_status: None,
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}

pub fn blotted_lip() -> CosmeticItem {
    CosmeticItem {
        id: "kc-starter-lips-02".to_string(),
        name: "Blotted Lip".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "LIPS".to_string(),
        micro_category: "LIP_BALM".to_string(),
        color_hex: "#B72227".to_string(),
        shade_name: Some("Bee's Knees Crimson".to_string()),
        image_url: "https://cdn.kocolor.com/assets/products/blotted.png".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/assets/thumbs/blotted_256.png".to_string(),
        price: Some(12.0),
        notes: Some("Matte blotted balm with sheer buildable color.".to_string()),
        formulation: Some("STICK".to_string()),
        chemistry_base: Some("WAX".to_string()),
        finish: Some("MATTE".to_string()),
        coverage: Some("SHEER".to_string()),
        temperature: Some("COOL".to_string()),
        volume: Some("3.5g".to_string()),
        pao_months: Some(12),
        expiry_date: None,
        batch_code: None,
        hero_ingredient: Some("Squalane".to_string()),
        skin_compatibility: Some("Sensitive Lips".to_string()),
        contains_fragrance: Some(false),
        eco_score: Some("A".to_string()),
        instructions: Some("Swipe directly onto lips for a blotted stain effect.".to_string()),
        ingredients: vec!["Squalane".to_string(), "Microcrystalline Wax".to_string(), "Red 7 Lake".to_string()],
        allergens: vec![],
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: None,
        ritual_placement: None,
        fda_recall_status: None,
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}
