use crate::CosmeticItem;

pub fn purifying_gel_cleanser() -> CosmeticItem {
    CosmeticItem {
        id: "kc-starter-prep-01".to_string(),
        name: "Purifying Gel Cleanser".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "PREP".to_string(),
        micro_category: "CLEANSER".to_string(),
        color_hex: "#F4F6F0".to_string(),
        shade_name: Some("Clear Crystal".to_string()),
        image_url: "https://cdn.kocolor.com/assets/products/cleanser.png".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/assets/thumbs/cleanser_256.png".to_string(),
        price: Some(18.0),
        notes: Some("Gentle daily foaming cleanser that balances skin pH.".to_string()),
        formulation: Some("GEL".to_string()),
        chemistry_base: Some("WATER".to_string()),
        finish: Some("NATURAL".to_string()),
        coverage: Some("SHEER".to_string()),
        temperature: Some("NEUTRAL".to_string()),
        volume: Some("150ml".to_string()),
        pao_months: Some(12),
        expiry_date: None,
        batch_code: None,
        hero_ingredient: Some("Niacinamide".to_string()),
        skin_compatibility: Some("All Skin Types".to_string()),
        contains_fragrance: Some(false),
        eco_score: Some("A".to_string()),
        instructions: Some("Lather with water and massage onto wet skin. Rinse thoroughly.".to_string()),
        ingredients: vec!["Water".to_string(), "Glycerin".to_string(), "Sodium Cocoyl Glycinate".to_string(), "Citric Acid".to_string()],
        allergens: vec![],
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: None,
        ritual_placement: None,
        fda_recall_status: None,
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}

pub fn luminescent_c_serum() -> CosmeticItem {
    CosmeticItem {
        id: "kc-starter-prep-02".to_string(),
        name: "Luminescent C Serum".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "PREP".to_string(),
        micro_category: "SERUM".to_string(),
        color_hex: "#FFF8E7".to_string(),
        shade_name: Some("Luminous Glow".to_string()),
        image_url: "https://cdn.kocolor.com/assets/products/serum.png".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/assets/thumbs/serum_256.png".to_string(),
        price: Some(28.0),
        notes: Some("Antioxidant Vitamin C treatment for skin radiance.".to_string()),
        formulation: Some("LIQUID".to_string()),
        chemistry_base: Some("WATER".to_string()),
        finish: Some("RADIANT".to_string()),
        coverage: Some("SHEER".to_string()),
        temperature: Some("NEUTRAL".to_string()),
        volume: Some("30ml".to_string()),
        pao_months: Some(6),
        expiry_date: None,
        batch_code: None,
        hero_ingredient: Some("Vitamin C".to_string()),
        skin_compatibility: Some("Normal to Dry".to_string()),
        contains_fragrance: Some(false),
        eco_score: Some("A".to_string()),
        instructions: Some("Apply 3-4 drops to clean skin prior to moisturizing.".to_string()),
        ingredients: vec!["Water".to_string(), "Ascorbic Acid".to_string(), "Propanediol".to_string(), "Sodium Hyaluronate".to_string()],
        allergens: vec![],
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: None,
        ritual_placement: None,
        fda_recall_status: None,
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}

pub fn melt_in_milk_sunscreen() -> CosmeticItem {
    CosmeticItem {
        id: "kc-starter-prep-03".to_string(),
        name: "Melt-in Milk Sunscreen".to_string(),
        brand: "KoColor".to_string(),
        macro_category: "PREP".to_string(),
        micro_category: "SPF".to_string(),
        color_hex: "#FFFFFF".to_string(),
        shade_name: Some("Invisible Shield".to_string()),
        image_url: "https://cdn.kocolor.com/assets/products/spf.png".to_string(),
        thumbnail_url: "https://cdn.kocolor.com/assets/thumbs/spf_256.png".to_string(),
        price: Some(22.0),
        notes: Some("Broad-spectrum SPF 50+ lightweight facial fluid.".to_string()),
        formulation: Some("LIQUID".to_string()),
        chemistry_base: Some("WATER".to_string()),
        finish: Some("SATIN".to_string()),
        coverage: Some("SHEER".to_string()),
        temperature: Some("NEUTRAL".to_string()),
        volume: Some("50ml".to_string()),
        pao_months: Some(12),
        expiry_date: None,
        batch_code: None,
        hero_ingredient: Some("Cell-Ox Shield".to_string()),
        skin_compatibility: Some("Sensitive Skin".to_string()),
        contains_fragrance: Some(false),
        eco_score: Some("A".to_string()),
        instructions: Some("Apply generously 15 minutes before sun exposure.".to_string()),
        ingredients: vec!["Water".to_string(), "Homosalate".to_string(), "Silica".to_string(), "Niacinamide".to_string()],
        allergens: vec![],
        is_vegan: Some(true),
        is_cruelty_free: Some(true),
        recycling_instructions: None,
        ritual_placement: None,
        fda_recall_status: None,
        fda_adverse_event_count: 0,
        fda_clinical_warnings: vec![],
        fda_top_reactions: vec![],
        fda_active_ingredients: vec![],
        fda_data_verified: true,
    }
}
